"""Add fall_cooldown

Revision ID: 87ece1774913
Revises: a7b3f9c1d2e4
Create Date: 2026-06-21 22:11:25.312263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ece1774913'
down_revision: Union[str, Sequence[str], None] = 'a7b3f9c1d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('fall_cooldown', sa.Integer(), nullable=False, server_default='15'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'fall_cooldown')
    # ### end Alembic commands ###
