"""Add stream_timeout to devices

Revision ID: a6efb11dc16b
Revises: e6b09701f3d5
Create Date: 2026-06-25 15:43:43.954176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6efb11dc16b'
down_revision: Union[str, Sequence[str], None] = 'e6b09701f3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('stream_timeout', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'stream_timeout')
    # ### end Alembic commands ###
