"""Add telemetry_interval to devices

Revision ID: cade8bab7f74
Revises: f1eda2d1e58f
Create Date: 2026-06-14 01:15:21.976610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cade8bab7f74'
down_revision: Union[str, Sequence[str], None] = 'f1eda2d1e58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('telemetry_interval', sa.Integer(), nullable=False, server_default='5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'telemetry_interval')
    # ### end Alembic commands ###
