"""Add org_id to devices

Revision ID: f1eda2d1e58f
Revises: 56ec4e5d8c21
Create Date: 2026-05-08 16:47:02.166429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1eda2d1e58f'
down_revision: Union[str, Sequence[str], None] = '56ec4e5d8c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable
    op.add_column('devices', sa.Column('org_id', sa.UUID(), nullable=True))
    
    # 2. Populate org_id for existing devices
    # Try to copy from wearer's org_id
    op.execute("""
        UPDATE devices 
        SET org_id = wearers.org_id 
        FROM wearers 
        WHERE devices.current_wearer_id = wearers.id
    """)
    
    # For devices still without org_id (no wearer), use the first organization
    op.execute("""
        UPDATE devices 
        SET org_id = (SELECT id FROM organizations LIMIT 1)
        WHERE org_id IS NULL
    """)
    
    # 3. Set to NOT NULL and add FK
    op.alter_column('devices', 'org_id', nullable=False)
    op.create_foreign_key(None, 'devices', 'organizations', ['org_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'org_id')
    # ### end Alembic commands ###
